preload = /home/bro/gitrepos/github/dotfiles/home/bro/wallpapers/wallhaven-qrgl87.jpg
wallpaper = ,/home/bro/gitrepos/github/dotfiles/home/bro/wallpapers/wallhaven-qrgl87.jpg

ipc = true
splash = false
