preload = /home/bro/gitrepos/github/dotfiles/home/bro/wallpapers/wallhaven-7jwdpo.jpg
wallpaper = ,/home/bro/gitrepos/github/dotfiles/home/bro/wallpapers/wallhaven-7jwdpo.jpg

ipc = true
splash = false
