#wallpaper {
#    monitor = 
#    path = /home/bro/Media/Wallpapers/wallhaven-3q5ex3.jpg
#    fit_mode = fill
#}
#
#splash = false


preload = /home/bro/Media/Wallpapers/wallhaven-21dw6m.jpg
wallpaper = ,/home/bro/Media/Wallpapers/wallhaven-21dw6m.jpg

splash = false
