# Generated by nixos-generate-config for mixi. Keep machine-specific devices
# here and make policy changes in configuration.nix.
{ lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "uas"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/vg-nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FD90-1A14";
    fsType = "vfat";
    # Root only: the initrd files here have the unlock host key and the edge
    # tunnel key appended (fuji and the desktops had this already).
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ { device = "/dev/mapper/vg-swap"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
