# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c85d2069-9d8e-4b23-aa07-7ac58e8a2645";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c85d2069-9d8e-4b23-aa07-7ac58e8a2645".device = "/dev/disk/by-uuid/c85d2069-9d8e-4b23-aa07-7ac58e8a2645";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A600-456D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d42cecf7-c82c-4396-83d7-20a1b651a281"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
