# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-97938d30-0967-47e3-9b04-32eeacf45e1e";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-97938d30-0967-47e3-9b04-32eeacf45e1e".device = "/dev/disk/by-uuid/97938d30-0967-47e3-9b04-32eeacf45e1e";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-97938d30-0967-47e3-9b04-32eeacf45e1e";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-97938d30-0967-47e3-9b04-32eeacf45e1e";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9F4D-ADD5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # No swap. The installer set up an encrypted swap partition (nvme0n1p3,
  # luks-b015eb32-...) but it was never unlocked at boot, so fuji has always
  # run without it and systemd waited forever for the device on every boot
  # and rebuild. Kubernetes prefers no swap anyway.
  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
